apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: newfrontend
  name: newfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newfrontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: newfrontend
        tier: frontend
    spec:
      containers:
      - image: nickhabermann2001/todo_newfrontend
        env:
        - name: BACKEND_URL
          value: "http://localhost:8080"
        name: lab
        resources: {}
status: {}
