networks:
  todonet:

services:

  ### APPLICATION PART

  postgresdb:
    image: postgres
    networks:
      - todonet
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=matthias
      - POSTGRES_DB=mydb

  todobackend-springboot:
    image: maeddes/todobackend-springboot:hse24
    networks:
      - todonet
    build:
      context: ./todobackend-springboot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgresdb

  frontend:
    container_name: new-frontend
    build:
      context: ./todoui-mithril
      dockerfile: Dockerfile
    depends_on:
      - todobackend-springboot
    networks:
      - todonet
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://localhost:8080

